// AUTH MODULE
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const REMEMBER_PASSWORD = 'REMEMBER_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'

// NEWLETTER MODULE
export const SUBSCRIBE_TO_NEWSLETTER = 'SUBSCRIBE_TO_NEWSLETTER'

// USERS MODULE
export const FETCH_USERS = 'FETCH_USERS'
export const USER_UNPAY = 'USER_UNPAY'
export const USER_PAY = 'USER_PAY'
export const UPDATE_USER = 'UPDATE_USER'
export const SELECTED_USER = 'SELECTED_USER'

// EVENTS
export const FETCH_EVENTS = 'FETCH_EVENTS'
export const REGISTER_CURRENT_USER_TO_EVENT = 'REGISTER_CURRENT_USER_TO_EVENT'
export const UNREGISTER_CURRENT_USER_TO_EVENT = 'UNREGISTER_CURRENT_USER_TO_EVENT'
export const UNREGISTER_CURRENT_USER_TO_GROUP_EVENT = 'UNREGISTER_CURRENT_USER_TO_GROUP_EVENT'
export const UNREGISTER_USER_TO_EVENT = 'UNREGISTER_USER_TO_EVENT'
export const REMOVE_USER_FROM_EVENT = 'REMOVE_USER_FROM_EVENT'
export const REGISTER_USER_TO_EVENT = 'REGISTER_USER_TO_EVENT'
export const UNREGISTER_ALL_EVENTS = 'UNREGISTER_ALL_EVENTS'
export const REGISTER_GROUP_TO_EVENT = 'REGISTER_GROUP_TO_EVENT'
export const UNREGISTER_GROUP_TO_EVENT = 'UNREGISTER_GROUP_TO_EVENT'

// NUMBERS
export const FETCH_NUMBERS = 'FETCH_NUMBERS'
export const ASSIGN_NUMBER_TO_USER = 'ASSIGN_NUMBER_TO_USER'
export const UNASSIGN_NUMBER_TO_USER = 'UNASSIGN_NUMBER_TO_USER'
export const UNASSIGN_NUMBERS_TO_USER = 'UNASSIGN_NUMBERS_TO_USER'

// NUMBERS
export const FETCH_TICKETS = 'FETCH_TICKETS'
