// USERS
export const SELECTED_USER = 'SELECTED_USER'
export const SET_USERS = 'SET_USERS'
export const SET_SELECTED_USER_NUMBERS = 'SET_SELECTED_USER_NUMBERS'
export const ADD_NUMBER_TO_SELECTED_USER_NUMBERS = 'ADD_NUMBER_TO_SELECTED_USER_NUMBERS'
export const REMOVE_NUMBER_TO_SELECTED_USER_NUMBERS = 'REMOVE_NUMBER_TO_SELECTED_USER_NUMBERS'
export const SET_SELECTED_USER_PAYMENT = 'SET_SELECTED_USER_PAYMENT'
export const SET_USER_PAYMENT_STATE = 'SET_USER_PAYMENT_STATE'

// AUTH
export const LOGGED = 'LOGGED'
export const USER = 'USER'

// NEWSLETTER
export const NEWSLETTER_EMAIL = 'NEWSLETTER_EMAIL'

// EVENTS
export const SET_EVENTS = 'SET_EVENTS'
export const SET_EVENT_AS_INSCRIBED = 'SET_EVENT_AS_INSCRIBED'
export const SET_GROUP_EVENT_AS_INSCRIBED = 'SET_GROUP_EVENT_AS_INSCRIBED'
export const SET_EVENT_AS_UNSUBSCRIBED = 'SET_EVENT_AS_UNSUBSCRIBED'
export const SET_GROUP_EVENT_AS_UNSUBSCRIBED = 'SET_GROUP_EVENT_AS_UNSUBSCRIBED'
export const UNSET_EVENT_AS_LOADING = 'UNSET_EVENT_AS_LOADING'
export const SET_EVENT_AS_LOADING = 'SET_EVENT_AS_LOADING'
export const UNREGISTER_SELECTED_USER_TO_EVENT = 'UNREGISTER_SELECTED_USER_TO_EVENT'
export const REGISTER_SELECTED_USER_TO_EVENT = 'REGISTER_SELECTED_USER_TO_EVENT'
export const SET_SELECTED_USER_EVENTS = 'SET_SELECTED_USER_EVENTS'
export const REMOVE_GROUP_FROM_EVENT = 'REMOVE_GROUP_FROM_EVENT'
export const REMOVE_USER_FROM_EVENT = 'REMOVE_USER_FROM_EVENT'

// NUMBERS
export const LAST_ASSIGNED_NUMBER = 'LAST_ASSIGNED_NUMBER'
export const SET_NUMBERS = 'SET_NUMBERS'
export const ASSIGN_USER_TO_NUMBER = 'ASSIGN_USER_TO_NUMBER'
export const UNASSIGN_USER_TO_NUMBER = 'UNASSIGN_USER_TO_NUMBER'

// NUMBERS
export const SET_TICKETS = 'SET_TICKETS'
